trigger:
 tags:
   include:
     - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Get identity details'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az rest -u https://app.vssps.visualstudio.com/_apis/profile/profiles/me --resource 499b84ac-1321-427f-aa17-267ca6975798

- script: |
    npm install -g @vscode/vsce
    npm install
  displayName: "Install vsce and dependencies"

# Publish
- task: AzureCLI@2
  displayName: 'Publish using managed identity'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      vsce publish --azure-credential